// 📁 SAVE AS: src/app/privacy/page.tsx

"use client";
import Navbar from "@/components/Navbar";
import Link from "next/link";

export default function PrivacyPage() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen bg-white text-slate-900">
        <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6">
          <div className="text-center mb-12">
            <h1 className="text-3xl font-bold sm:text-4xl">Privacy Policy</h1>
            <span className="inline-block mt-4 rounded-full bg-slate-100 px-4 py-2 text-sm font-medium text-slate-700">
              Last updated: May 2026
            </span>
          </div>

          <div className="space-y-8">
            <section className="rounded-lg bg-slate-50 p-6">
              <h2 className="text-xl font-bold mb-4">1. Introduction</h2>
              <p className="mb-4">
                QuizAI is operated by <strong>Modern AI Softech</strong>. This
                Privacy Policy explains how we collect, use, and protect your
                information when you use our quiz generation service.
              </p>
              <p>
                By using QuizAI, you agree to the collection and use of
                information in accordance with this policy. We are committed to
                ensuring your personal data is protected.
              </p>
            </section>

            <section className="rounded-lg bg-slate-50 p-6">
              <h2 className="text-xl font-bold mb-4">
                2. Data Collection & Storage
              </h2>
              <ul className="list-disc list-inside space-y-3 text-slate-700">
                <li>
                  <strong>Account Information:</strong> We collect your email
                  address and name via <strong>Supabase Auth</strong> when you
                  sign up or upgrade to a Pro plan.
                </li>
                <li>
                  <strong>Quiz Content (Free Plan):</strong> Quizzes generated
                  on the Free plan are stored in your browser's{" "}
                  <strong>localStorage</strong> only and are never sent to our
                  database.
                </li>
                <li>
                  <strong>Quiz Content (Pro Plan):</strong> To provide
                  cross-device access, quizzes generated by Pro users are
                  securely stored in our <strong>Supabase database</strong>.
                </li>
                <li>
                  <strong>Device Data:</strong> We collect a unique device
                  fingerprint and basic browser information (stored in our{" "}
                  <code>user_sessions</code> table) to enforce a 3-device limit
                  for Pro accounts.
                </li>
              </ul>
            </section>

            <section className="rounded-lg bg-slate-50 p-6">
              <h2 className="text-xl font-bold mb-4">
                3. Third-Party Services
              </h2>
              <p className="mb-4">
                We partner with the following services to provide QuizAI:
              </p>
              <ul className="list-disc list-inside space-y-2 text-slate-700">
                <li>
                  <strong>Supabase:</strong> Handles database storage, user
                  profiles, and secure authentication.
                </li>
                <li>
                  <strong>Lemon Squeezy:</strong> Our Merchant of Record for all
                  payment processing and subscription billing.
                </li>
                <li>
                  <strong>Groq AI & OpenRouter:</strong> Processes topics to
                  generate quiz questions (no personal data is shared with these
                  AI providers).
                </li>
                <li>
                  <strong>Vercel:</strong> Hosts our application infrastructure.
                </li>
              </ul>
            </section>

            <section className="rounded-lg bg-slate-50 p-6">
              <h2 className="text-xl font-bold mb-4">4. Data Security</h2>
              <ul className="list-disc list-inside space-y-2 text-slate-700">
                <li>
                  All data is transmitted via secure{" "}
                  <strong>HTTPS encryption</strong>.
                </li>
                <li>
                  Authentication is managed through secure, server-side cookies.
                </li>
                <li>
                  Sensitive payment information is handled entirely by Lemon
                  Squeezy; we never see or store your credit card details.
                </li>
              </ul>
            </section>

            <section className="rounded-lg bg-slate-50 p-6">
              <h2 className="text-xl font-bold mb-4">5. Your Rights</h2>
              <p className="mb-4">
                Depending on your location, you may have the following rights:
              </p>
              <ul className="list-disc list-inside space-y-2 text-slate-700">
                <li>
                  The right to access, update, or delete the personal
                  information we have on you.
                </li>
                <li>
                  The right to clear your browser's <code>localStorage</code> at
                  any time to remove local quiz history.
                </li>
                <li>
                  The right to cancel your subscription through your Lemon
                  Squeezy billing portal.
                </li>
              </ul>
            </section>

            <section className="rounded-lg bg-slate-50 p-6">
              <h2 className="text-xl font-bold mb-4">6. Contact Us</h2>
              <p className="text-slate-700">
                If you have questions about this policy or wish to request data
                deletion, please contact us at:{" "}
                <strong>zahid.14u@gmail.com</strong>.
              </p>
            </section>
          </div>

          <div className="mt-12 text-center">
            <Link href="/terms" className="text-purple-600 hover:underline">
              View our Terms and Conditions
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
